/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppDetailsupprimer {
    'match': MatchResults;
    'retour': RouterHistory;
  }
  interface AppDetailsupprimerAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
    'retour'?: RouterHistory;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppHommy {
    'load': () => void;
  }
  interface AppHommyAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ArticleList {
    'arts': any[];
  }
  interface ArticleListAttributes extends StencilHTMLAttributes {
    'arts'?: any[];
  }

  interface EditerArticle {
    'match': MatchResults;
    'retour': RouterHistory;
  }
  interface EditerArticleAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
    'retour'?: RouterHistory;
  }

  interface MyApp {}
  interface MyAppAttributes extends StencilHTMLAttributes {}

  interface NewArticle {}
  interface NewArticleAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppDetailsupprimer': Components.AppDetailsupprimer;
    'AppHome': Components.AppHome;
    'AppHommy': Components.AppHommy;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'ArticleList': Components.ArticleList;
    'EditerArticle': Components.EditerArticle;
    'MyApp': Components.MyApp;
    'NewArticle': Components.NewArticle;
  }

  interface StencilIntrinsicElements {
    'app-detailSupprimer': Components.AppDetailsupprimerAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-hommy': Components.AppHommyAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'article-list': Components.ArticleListAttributes;
    'editer-article': Components.EditerArticleAttributes;
    'my-app': Components.MyAppAttributes;
    'new-article': Components.NewArticleAttributes;
  }


  interface HTMLAppDetailsupprimerElement extends Components.AppDetailsupprimer, HTMLStencilElement {}
  var HTMLAppDetailsupprimerElement: {
    prototype: HTMLAppDetailsupprimerElement;
    new (): HTMLAppDetailsupprimerElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppHommyElement extends Components.AppHommy, HTMLStencilElement {}
  var HTMLAppHommyElement: {
    prototype: HTMLAppHommyElement;
    new (): HTMLAppHommyElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLArticleListElement extends Components.ArticleList, HTMLStencilElement {}
  var HTMLArticleListElement: {
    prototype: HTMLArticleListElement;
    new (): HTMLArticleListElement;
  };

  interface HTMLEditerArticleElement extends Components.EditerArticle, HTMLStencilElement {}
  var HTMLEditerArticleElement: {
    prototype: HTMLEditerArticleElement;
    new (): HTMLEditerArticleElement;
  };

  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLNewArticleElement extends Components.NewArticle, HTMLStencilElement {}
  var HTMLNewArticleElement: {
    prototype: HTMLNewArticleElement;
    new (): HTMLNewArticleElement;
  };

  interface HTMLElementTagNameMap {
    'app-detailSupprimer': HTMLAppDetailsupprimerElement
    'app-home': HTMLAppHomeElement
    'app-hommy': HTMLAppHommyElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'article-list': HTMLArticleListElement
    'editer-article': HTMLEditerArticleElement
    'my-app': HTMLMyAppElement
    'new-article': HTMLNewArticleElement
  }

  interface ElementTagNameMap {
    'app-detailSupprimer': HTMLAppDetailsupprimerElement;
    'app-home': HTMLAppHomeElement;
    'app-hommy': HTMLAppHommyElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'article-list': HTMLArticleListElement;
    'editer-article': HTMLEditerArticleElement;
    'my-app': HTMLMyAppElement;
    'new-article': HTMLNewArticleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
